# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-12 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180312_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
